#!/bin/bash
#MSUB -N msmaccelerator-test1
#MSUB -l nodes=1:ppn=6:gpus=6
#MSUB -l walltime=13:00:00
#MSUB -q shortq
#MSUB -d /home/harrigan/projects/msmaccelerator2.villin/project/

cd /home/harrigan/projects/msmaccelerator2.villin/project/
mkdir -p logs
nvidia-smi &>logs/msmaccelerator-test1.out

for i in `seq 1 10`
do
  
  accelerator OpenMM --device_index=0 &>logs/msmaccelerator-test1-$i-0.out &
  sleep 10
  
  accelerator OpenMM --device_index=1 &>logs/msmaccelerator-test1-$i-1.out &
  sleep 10
  
  accelerator OpenMM --device_index=2 &>logs/msmaccelerator-test1-$i-2.out &
  sleep 10
  
  accelerator OpenMM --device_index=3 &>logs/msmaccelerator-test1-$i-3.out &
  sleep 10
  
  accelerator OpenMM --device_index=4 &>logs/msmaccelerator-test1-$i-4.out &
  sleep 10
  
  accelerator OpenMM --device_index=5 &>logs/msmaccelerator-test1-$i-5.out &
  sleep 10
  

  wait
  accelerator model >>logs/msmaccelerator-test1-$i.out 2>&1
done